"""empty message

Revision ID: 139cf6a2d2d9
Revises: 
Create Date: 2018-03-08 14:48:12.049167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '139cf6a2d2d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('albums', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('styles', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('websites', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('bio', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bands')
    # ### end Alembic commands ###
