"""empty message

Revision ID: 286176a8491a
Revises: 
Create Date: 2018-02-21 15:25:42.219750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '286176a8491a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('albums', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('styles', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('websites', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('bio', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bands')
    # ### end Alembic commands ###
